# Generated by Django 2.2 on 2019-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enr_no', models.CharField(max_length=12, verbose_name='Enrollment number')),
                ('enr_year', models.PositiveSmallIntegerField(default=2000, verbose_name='Enrollment year')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('degree', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
