# Generated by Django 2.2 on 2019-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20190426_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Technical skills'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Enginnering'), ('IT', 'Information Technology'), ('MAE', 'Mechanical and Automation Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='enr_year',
            field=models.PositiveSmallIntegerField(default=2015, verbose_name='Enrollment year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(verbose_name='GPA'),
        ),
    ]
